# Generated by Django 6.0.5 on 2026-05-26 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код валюти')),
                ('name', models.CharField(max_length=100, verbose_name='Назва валюти')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюти',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс купівлі')),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс продажу')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Курс валюти',
                'verbose_name_plural': 'Курси валют',
                'ordering': ['-date', 'currency__code'],
                'unique_together': {('currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата збереження')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час збереження')),
                ('rates', models.ManyToManyField(to='rates.exchangerate', verbose_name='Курси валют')),
            ],
            options={
                'verbose_name': 'Снапшот дня',
                'verbose_name_plural': 'Снапшоти дня',
                'ordering': ['-date'],
            },
        ),
    ]
